/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taehyun.kim;

import org.junit.Test;

import taehyun.kim.solution.Lotto;
import taehyun.kim.solution.replaceStrToNum;

import static org.junit.Assert.*;

import org.junit.Assert;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void lotto(){
        Lotto lotto = new Lotto();
        int[] lottos = {0,0,0,0,0,0};
        int[] win_nums = {12,7,8,9,10,11};
        int[] result = {1,6};
        int[] answer = lotto.solution(lottos, win_nums);

        Assert.assertArrayEquals(result, answer);
    }

    @Test
    public void replaceStrToNumTest(){
        replaceStrToNum test = new replaceStrToNum();
        String s = "2three45sixseven";
        int result = 234567;
        Assert.assertEquals(result, test.solution(s));
    }
}
